# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  client-build:

    runs-on: self-hosted
    
    defaults:
       run:
         working-directory: ./client/
    #strategy:
      #matrix:
        #node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
    - run: pwd
    #- run: cd client
    - run: cat package.json
    - run: npm i
    - run: cat package.json
    - run: npm run prod-build
    - run: pm2 reload client
  server-build:
    runs-on: self-hosted
    defaults:
       run:
         working-directory: ./server/
    steps:
    - uses: actions/checkout@v3
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'npm'
    - run: pwd
    #- run: cd client

    - run: cat package.json
    - run: npm i
    - run: npm run prod-build
    - run: pm2 reload server